baseurl = "https://redundancy.github.io/blog/"
languageCode = "en-us"
title = "The Nexus"
publishDir = "docs"
disqusShortname = "nexusblog-1"

[Author]
  name = "Daniel Speed"
  github = "Redundancy"
