baseurl = "https://redundancy.github.io/blog/"
locale = "en-us"
title = "The Nexus"

[module]
  [[module.imports]]
    path = "github.com/halogenica/beautifulhugo"

[services]
  [services.disqus]
    shortname = "nexusblog-1"

[Author]
  name = "Daniel Speed"
  github = "Redundancy"
